Publish actual inputs state on start up
wirenboard/wb-mqtt-gpio pull request #29
Opened 2021-09-19 07:33 UTC by KraPete

2021-09-19 08:11 UTC, evgeny-boger requested changes

2021-09-19 08:11 UTC, evgeny-boger commented on gpio_chip_driver.cpp
> +        std::copy_if(lines.begin(), lines.end(), std::back_inserter(linesToRead), shouldReadValue);
а чем вот это лучше просто цикла?

2021-09-20 05:33 UTC, KraPete commented on gpio_chip_driver.cpp
> +        std::copy_if(lines.begin(), lines.end(), std::back_inserter(linesToRead), shouldReadValue);
Это более декларативно. Поменял на цикл.

2021-09-20 09:05 UTC, evgeny-boger approved these changes

2021-09-20 09:07 UTC, merged