Feature/52710 tidy up logs
wirenboard/wb-mqtt-gpio pull request #41
Opened 2022-09-06 19:53 UTC by rkochkin

Поменял уровень некоторых сообщений лога на отладочный.
Добавил в настройку включение отладочных сообщений.

2022-09-12 11:39 UTC, rkochkin commented on main.cpp
> +    DebugLevel CommandLineDebugLevel = DebugLevel::NONE;
Убрал глобальную переменную.

2022-09-12 11:46 UTC, rkochkin commented on gpio_chip_driver.cpp
> +        LOG(Debug) << "Initialized output " << line->DescribeShort();
Сделал Info для этого сообщения

2022-10-13 15:42 UTC, webconn requested changes

2022-10-13 15:42 UTC, webconn commented on debian/changelog
> +  * Changed severity level for debug log
Мы теперь записи в лог стараемся писать в повелительном наклонении: https://github.com/wirenboard/codestyle/blob/master/guidelines/debianization.md#%D0%BE-%D1%87%D0%B5%D0%B9%D0%BD%D0%B4%D0%B6%D0%BB%D0%BE%D0%B3%D0%B0%D1%85

2022-10-13 15:42 UTC, webconn commented on gpio_chip_driver.cpp
> +    LOG(Info) << line->Describe() << " is used by '" << line->GetConsumer() << "'.";
Всё ещё актуально

2022-10-13 15:42 UTC, webconn commented on gpio_chip_driver.cpp
> +        if (oldValue != newValue) {
Тоже актуально

2022-10-17 08:12 UTC, rkochkin commented on debian/changelog
> +  * Changed severity level for debug log
Поправил

2022-10-18 07:23 UTC, rkochkin commented on gpio_chip_driver.cpp
> +        if (oldValue != newValue) {
Поправил

2022-10-18 07:23 UTC, rkochkin commented on gpio_chip_driver.cpp
> +    LOG(Info) << line->Describe() << " is used by '" << line->GetConsumer() << "'.";
Поправил

2022-10-19 06:47 UTC, webconn approved these changes

2022-10-28 10:36 UTC, KraPete approved these changes

2022-11-02 13:01 UTC, merged