Feature/51182 new debounce
wirenboard/wb-mqtt-gpio pull request #44
Opened 2022-09-23 07:16 UTC by vdromanov

Раньше:
смотрели время между полученным событием и предыдущим. Время > порога - отфильтровываем полученное событие

Сейчас:
используем идею эмбеддеров. Внедрен таймер. Если таймер натикал сколько-то раз, а значение на gpio не поменялось - значение корректно. Выкинул всю старую фильтрацию дребезга.

Концептуально: в обработчике прерывания запоминаем время его возникновения и кладем gpio-line в set "недавно сработавших". Рядом крутится таймер и смотрит в "недавно сработавшие". Если оттикало нужное время без изменения - обновляем значение в mqtt и убираем line из "недавно сработавших".

Погонял у себя (wb67, 4xWD-14, 2xR1G-16) - разницы со старым подходом не видно. Положил дебку на форум - пользователь молчит.

сверху - старая фильтрация дребезга; снизу - новая. Часто жму на кнопку на wd-14
![2022-09-23_00-43-41](https://user-images.githubusercontent.com/25829054/191908946-17d13d26-0408-42b3-8ef5-95bdf67d6eee.png)

CPU вроде не сильно жрет (было - стало)
![2022-09-23_00-41-35](https://user-images.githubusercontent.com/25829054/191909143-394f5ec1-b820-4c19-a149-1eddb6d95e9f.png)
![2022-09-23_00-37-23](https://user-images.githubusercontent.com/25829054/191909180-e45b2467-85fb-406f-b4c1-3bbd8eda27f9.png)

2022-09-23 08:08 UTC, KraPete requested changes
Мне не очень нравится.
1. У нас тут незащищённый се..., тьфу, совместный доступ к памяти из нескольких потоков.
2. Таймер потоком, как-то простовато :) Прям хочется что-то через epoll сделать, чтоб в том же цикле мониторилось.
3. Тестов нет вообще. Конечно, их и сначала не было, но если б получилось вынести обратоку событий и её тестировать, было бы прямо круто.

2022-10-05 06:56 UTC, vdromanov commented
поток убрал, epoll добавил, каких-то тестиков сделал:)
(по возможности не менял логику)
работает, как раньше, cpu ест +- как раньше (5-6% с кучей wbio-модулей)

картинка - уже с таймером на epoll
![2022-10-05_09-33-26](https://user-images.githubusercontent.com/25829054/193998913-e8436f55-0b32-4b39-a44d-c74a06075a47.png)

2022-10-05 10:46 UTC, KraPete commented
1. Вообще я имел ввиду немного не то. Не симулировать поток через таймер, а сделать для каждой линии по таймеру. Положить дескрипторы таймеров в тот же `epfd`, что и дескрипторы gpio. Запускать таймер по приходу события для конкретной линии. Тогда все события (и срабатывание таймера и срабатывание на линии) будут обрабатываться одним `epoll_wait`, сейчас же мы имеем по циклу на каждый чип, который вхолостую ест проц.
2. Есть нюанс с обработкой таймера. Например, мы увидели, что надо публиковать состояния нескольких линий. Публикация одного сообщения может занимать до 20мс. В результате все взведённые таймеры сработают, и мы увидим на них всех события, хотя в очереди уже могут лежать события по входам, которые отменяют срабатывание. @webconn Возможно, стоит обсудить как это сделать корректно.

2022-10-05 10:47 UTC, KraPete requested changes

2022-10-17 09:06 UTC, vdromanov commented on gpio_driver.cpp
> +void TGpioDriver::SetIntervalTimer(int tfd, uint16_t intervalMs)
готово

2022-10-17 09:06 UTC, vdromanov commented
вроде всё поправил, как обсуждали в пятницу

на железках погонял - мне всё нравится

2022-10-18 05:07 UTC, KraPete requested changes
Вопрос с последовательностью событий остаётся открытым.
Если мы запустили таймер и протупили где-то до следующего `epoll_wait`, можно получить одновременно срабатывание таймера и следующий фронт дребезга в очереди epoll. Будут ли они обработаны в хронологическом порядке? Или мы получим неотфильтрованное срабатывание?

2022-10-18 05:07 UTC, KraPete commented on test/config_test_data/good1/wb-mqtt-gpio.conf
> -      "debounce": 20000
Зачем изменили тест?

2022-10-18 05:20 UTC, KraPete commented
Верояно, стоит выгрести все события из `epoll`, отсортировать их по времени и уже отсортированный поток скармливать коду, который анализирует фронты.

2022-10-18 05:28 UTC, KraPete commented on gpio_line.cpp
>      if (Counter) {
Я имел ввиду подсчёт импульсов

2022-10-18 14:44 UTC, webconn reviewed
Мне всё нравится, но есть стилистические моменты и очепятки (докину вслед за Петром)

2022-10-18 14:44 UTC, webconn commented on test/debounce.test.cpp
> +    int debounceTimeuotUs = 50000;
`Timeout`

2022-10-18 14:44 UTC, webconn commented on gpio_chip_driver.cpp
> +        auto itFdTimers = Timers.find(fd);
Я бы тут написал как-нибудь, чтобы получился `if..else` с вызовом отдельных функций, вроде

```c++
for (int i = 0; i < ctx.Count; i++) {
  ...
  auto idFdTimers = Timers.find(fd);
  if (idFdTimers != Timers.end()) {
    HandleTimerInterrupt(idFdTimers->second);
  } else {
    HandleGpioInterrupt(fd)
  }
}
```

Так меньше уровней вложенности и проще читать / понимать.

Ну а ещё в MISRA, например, запрещают использовать `continue`, потому что логика превращается в лапшу и с уровнями вложенности больше 2-3 становится сложно воспринимать.

2022-10-18 23:01 UTC, vdromanov commented on gpio_line.h
> +                  TimerFd;
готово
переделал рядом, форматирование поправил

2022-10-18 23:01 UTC, vdromanov commented on gpio_line.h
> +                    ValueUnfiltered;
готово

2022-10-18 23:01 UTC, vdromanov commented on gpio_line.cpp
>      , Value(0)
упс, готово

2022-10-18 23:01 UTC, vdromanov commented on gpio_line.h
> +    TValue<uint8_t> Value,
неа, ругается

TValue оставил

2022-10-18 23:01 UTC, vdromanov commented on gpio_chip_driver.cpp
> +    close(oldTimerFd);
готово

в деструктор тоже добавил

2022-10-18 23:01 UTC, vdromanov commented on gpio_chip_driver.cpp
> +                close(line->GetTimerFd());
готово

2022-10-18 23:01 UTC, vdromanov commented on gpio_line.cpp
>      if (Counter) {
всё-таки поломалось, да

перетащил наполнение Counter из gpio_line в gpio_chip_driver (отфильтрованными значениями)

2022-10-18 23:02 UTC, vdromanov commented on config.h
> +    std::chrono::microseconds DebounceTimeout      = std::chrono::microseconds(50000);
это от старого дизайна осталось (где-то в интернетах про 50мс подсмотрел)

вернул 10

2022-10-18 23:03 UTC, vdromanov commented on test/config_test_data/good1/wb-mqtt-gpio.conf
> -      "debounce": 20000
не хотел отдельный тест делать для слишком большого debounce в конфиге

всё-таки сделал

2022-10-18 23:03 UTC, vdromanov commented on gpio_chip.cpp
> +    if (Fd) {
упс, готово

2022-10-18 23:03 UTC, vdromanov commented on gpio_chip_driver.cpp
> +	if (tfd == -1) {
упс, неожиданные табы

готово

2022-10-18 23:03 UTC, vdromanov commented on test/debounce.test.cpp
> +    int debounceTimeuotUs = 50000;
готово
(и рядом всё)

2022-10-18 23:03 UTC, vdromanov commented on gpio_chip_driver.cpp
> +        auto itFdTimers = Timers.find(fd);
готово

continue тоже убрал

2022-10-18 23:10 UTC, vdromanov commented
> Вопрос с последовательностью событий остаётся открытым. Если мы запустили таймер и протупили где-то до следующего `epoll_wait`, можно получить одновременно срабатывание таймера и следующий фронт дребезга в очереди epoll. Будут ли они обработаны в хронологическом порядке? Или мы получим неотфильтрованное срабатывание?

судя по [интернетам](https://stackoverflow.com/a/19114553), доке
![2022-10-19_02-11-20](https://user-images.githubusercontent.com/25829054/196561643-69328431-831a-456b-812d-b8a93186a6a8.png)
и наблюдаемому мной поведению - epoll_wait возврщает fds в порядке появления на них эвентов, что для нас - идеально!

2022-10-19 04:34 UTC, KraPete requested changes
Уже хорошо, но я ещё попридираюсь :)

2022-10-19 04:34 UTC, KraPete commented on gpio_line.cpp
> +    UpdateInfo();
Зачем тут `UpdateInfo`?

2022-10-19 04:34 UTC, KraPete commented on test/config_test_data/good3/wb-mqtt-gpio.conf.d/system.conf
> +      "debounce": 2000000
Почему оно тут поменялось?

2022-10-19 04:34 UTC, KraPete commented on config.cpp
> +        chrono::microseconds maxDebounceTimeoutUs = chrono::microseconds(999999);
А зачем мы ввели это ограничение?

2022-10-19 04:34 UTC, KraPete commented on config.cpp
> +                    << "us. Has set to " << maxDebounceTimeoutUs.count() << "us.";
Валидацию конфига надо делать JSON-схемой

2022-10-19 04:34 UTC, KraPete commented on gpio_chip_driver.cpp
> +                close(line->GetTimerFd());
Тогда `close` можно тут убрать.

2022-10-19 04:34 UTC, KraPete commented on gpio_chip_driver.cpp
> +        auto itFdLines = Lines.find(fd);
Это искать надо в `else`

2022-10-19 04:34 UTC, KraPete commented on gpio_chip_driver.cpp
> +    close(oldTimerFd);
Тогда всю машинерию тут вокруг `oldTimerFd` можно убрать

2022-10-19 04:34 UTC, KraPete commented on gpio_chip_driver.cpp
> +        if (gpioCounter) {
А нельзя это в `UpdateIfStable` делать? Кажется оно должно быть внутри `TGpioLine`, а не сбоку

2022-10-24 23:41 UTC, vdromanov commented on gpio_chip_driver.cpp
> +        if (gpioCounter) {
точно!

готово + почистил от несрабатывающей логики

2022-10-24 23:41 UTC, vdromanov commented on gpio_chip_driver.cpp
> +        auto itFdLines = Lines.find(fd);
готово

2022-10-24 23:41 UTC, vdromanov commented on config.cpp
> +                    << "us. Has set to " << maxDebounceTimeoutUs.count() << "us.";
немного переделал - валидация не нужна

2022-10-24 23:41 UTC, vdromanov commented on config.cpp
> +        chrono::microseconds maxDebounceTimeoutUs = chrono::microseconds(999999);
чтобы в timerfd_settime секунды-наносекунды не гонять
но что-то решение и правда - не очень

=> теперь убрал это ограничение => валидация в конфиге тоже не нужна => тест на это тоже убрал

2022-10-24 23:41 UTC, vdromanov commented on test/config_test_data/good3/wb-mqtt-gpio.conf.d/system.conf
> +      "debounce": 2000000
проглядел, когда ветки сливал
предполагаю, +- в это время на женкинсе кончилось место => не заругался на тесты

вернул обратно

2022-10-24 23:42 UTC, vdromanov commented on gpio_line.cpp
> +    UpdateInfo();
убрал

2022-10-24 23:42 UTC, vdromanov commented on gpio_chip_driver.cpp
> +                close(line->GetTimerFd());
готово

2022-10-24 23:42 UTC, vdromanov commented on gpio_chip_driver.cpp
> +    close(oldTimerFd);
готово

2022-10-25 03:49 UTC, KraPete requested changes

2022-10-25 03:49 UTC, KraPete commented on gpio_chip_driver.cpp
> +                isHandled = HandleTimerInterrupt(line);
Здесь мы сломали логику. Раньше, если что-то нашлось было стабильно true. Сейчас мы тут можем один раз присвоить true, а потом false

2022-10-25 13:02 UTC, KraPete approved these changes

2022-10-25 20:39 UTC, merged

2022-10-25 22:09 UTC, sikmir commented
Один новый тест фейлится у меня:
```sh
wb-mqtt-gpio> test/debounce.test.cpp:47: Failure
wb-mqtt-gpio> Expected equality of these values:
wb-mqtt-gpio>   fakeGpioLine->GetValue()
wb-mqtt-gpio>     Which is: '"' (34, 0x22)
wb-mqtt-gpio>   assumedGpioState
wb-mqtt-gpio>     Which is: '\x1' (1)
wb-mqtt-gpio> [  FAILED  ] TDebounceTest.value_is_stable (84 ms)
```
А на второй `TDebounceTest.value_is_unstable` ругается valgrind. На jenkins почему-то оба прошли.

2022-10-26 04:06 UTC, KraPete commented
> Один новый тест фейлится у меня:
> 
> ```shell
> wb-mqtt-gpio> test/debounce.test.cpp:47: Failure
> wb-mqtt-gpio> Expected equality of these values:
> wb-mqtt-gpio>   fakeGpioLine->GetValue()
> wb-mqtt-gpio>     Which is: '"' (34, 0x22)
> wb-mqtt-gpio>   assumedGpioState
> wb-mqtt-gpio>     Which is: '\x1' (1)
> wb-mqtt-gpio> [  FAILED  ] TDebounceTest.value_is_stable (84 ms)
> ```
> 
> А на второй `TDebounceTest.value_is_unstable` ругается valgrind. На jenkins почему-то оба прошли.

Ты абсолютно прав!!! Я прошлапил, что Вова передаёт ссылки на `shared_ptr`, которые в функции создаются.