Feature/new debounce backport
wirenboard/wb-mqtt-gpio pull request #46
Opened 2022-10-26 21:47 UTC by vdromanov

бекпорт свежих изменений по дребезгу в wb-2207

тут внезапно выяснилось, что std::chrono::floor завезли в c++17
хоть floor и чуть корректнее, нас, имхо, здесь устраивает и duration_cast

погонял на wb6.5, 2207; проверил, что округляется всё нормально

2022-10-27 05:58 UTC, webconn requested changes

2022-10-27 05:58 UTC, webconn commented on debian/changelog
> +  * internals: fix debounce-test to build on non-armhf, remove debian-source-format,
Не, давай в одну версию схлопнем

2022-10-27 17:16 UTC, vdromanov commented
нажать забыл :(

2022-10-28 14:42 UTC, webconn approved these changes

2022-10-31 06:16 UTC, merged