Add load_previous_state gpio parameter
wirenboard/wb-mqtt-gpio pull request #49
Opened 2023-04-14 15:52 UTC by ekateluv

добавила еще один параметр в схему, чтобы можно было явно указать что при следующем старте нужно загрузить значение в initial_state

2023-04-16 05:24 UTC, KraPete requested changes
Надо тесты

2023-04-17 10:18 UTC, sikmir commented on wb-mqtt-gpio.schema.json
> +                    "title": "Load and publicate previous state or set it to initial_state",
```suggestion
                    "title": "Load and publish previous state or set it to initial_state",
```

2023-04-18 06:01 UTC, KraPete requested changes
Хочу больше тестов. Надо именно проверить, что значение не восстанавливается, т.е. что не дёргается GPIO, и не публикуется ничего левого в топике.

2023-06-15 05:01 UTC, KraPete commented
@sikmir Посмотри, пожалуйста

2023-06-15 07:14 UTC, sikmir commented on Makefile
>  	-rm -rf build/debug
Nit:
```suggestion
	-rm -rf build
```

2023-06-15 07:24 UTC, sikmir commented on test/initial_state.test.cpp
> +        testRootDir += "config_test_data";
```suggestion
        testRootDir = GetDataFilePath("config_test_data");
```

2023-06-15 07:26 UTC, sikmir approved these changes

2023-06-21 12:17 UTC, KraPete commented
Rebase https://github.com/wirenboard/wb-mqtt-gpio/pull/52

2023-06-21 12:17 UTC, closed without merging