Add coverage report generation
wirenboard/wb-mqtt-gpio pull request #67
Opened 2024-09-27 07:37 UTC by sikmir

How to use (with devcontainer):
```sh
make test DEBUG=1
open build/debug/cov.html
```
Using wbdev:
```sh
DEB_BUILD_OPTIONS="debug check cov-fail-under=75 cov-report=cov.html" ./wbdev cdeb
```

2024-10-01 04:21 UTC, KraPete approved these changes

2024-10-03 04:23 UTC, KraPete requested changes

2024-10-03 04:23 UTC, KraPete commented on src/gpio_line.cpp
> +    // assert(Offset < AccessChip()->GetLineCount());
Давай, это вообще уберём. Мы всё равно не собираем DEBUG при автоматическом тестировании. Это место создаёт ложную уверенность, что мы что-то тут проверили. Лучше явный тест написать или явную проверку с выбросом исключения

2024-10-03 04:23 UTC, KraPete commented on src/gpio_line.cpp
> +    // assert(Fd > -1);
Аналогично

2024-10-03 06:43 UTC, sikmir commented on src/gpio_line.cpp
> +    // assert(Offset < AccessChip()->GetLineCount());
убрал

2024-10-03 06:43 UTC, sikmir commented on src/gpio_line.cpp
> +    // assert(Fd > -1);
убрал

2024-10-03 07:13 UTC, KraPete approved these changes

2024-10-04 13:41 UTC, merged